version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ../..
        target: /app/source
        read_only: false
      - type: volume
        source: build-output
        target: /app/build
    working_dir: /app/build
    command: sh -c "while true; do sleep 1000; done"

volumes:
  build-output: