#!/bin/bash

# Function to cleanup processes
cleanup() {
    echo "Shutting down services..."
    kill $(jobs -p)
    exit
}

trap cleanup SIGINT SIGTERM

# Start services
cargo run --release > backend.stdout.log 2> backend.stderr.log &
pushd frontend
trunk serve --release > frontend.stdout.log 2> frontend.stderr.log &
popd

# Follow just the most important logs
tail -f backend.stderr.log | sed 's/^/[Backend] /' &
tail -f frontend.stderr.log | sed 's/^/[Frontend] /' &

wait