[package]
name = "service_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
paho-mqtt = "0.12.5"
thiserror = "2.0.1"
ssh2 = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"  # If using YAML
once_cell = "1.18"