FROM arm64v8/debian:bookworm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    crossbuild-essential-arm64 \
    ccache \
    g++ \
    make \
    git \
    cmake \
    pkg-config \
    libopencv-dev \
    nlohmann-json3-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /build
