FROM arm64v8/debian:bookworm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    crossbuild-essential-arm64 \
    ccache \
    g++ \
    make \
    git \
    cmake \
    pkg-config \
    libasound2-dev \
    libssl-dev \
    nlohmann-json3-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /build
COPY services/core/CMakeLists.txt services/core/
COPY services services
RUN cd services/core && \
    cmake -B build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build
